spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

# JWT
jwt:
  secret: U2VxdWVuY2lhRGVDYXJhY3RlcmVzUGFyYUFzc2luYXJUb2tlbg==
  expiration: 86400000

# OpenAPI
openapi:
  server:
    url:
      dev: http://localhost:8080
      prod: https://ecommerce.pifrans.com